### ISSUE TITLE
Create a button to download the import Excel sheet that contains the validation

### ISSUE THREAD

**Issue by Anthony4m** [ePareto-Information-System/SORMAS-Project#109]
### Problem Description

- [x] Add a button to sormas cases import form to download the excel file that does validation
- [x] Create button to validate the required fields excel templates on multiple records
- [x] Create a button to export the template into csv
- [x]  Create a button to reset form
- [x] Testing and updating csv to ensure that upload works.

**Comment by isaacanip** [comment]
05.04.2023
![image](https://user-images.githubusercontent.com/60930711/230094771-230ab3c5-8b64-4d48-9a32-3a89b21c58bc.png)

**Comment by isaacanip** [comment]
Issue resolved.
