### ISSUE TITLE
Dashboard map: include cases/contacts that don't have location coordinates

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#13]
Original issue here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2066

**Comment by user-yormen** [comment]
Kindly follow the link 
https://github.com/GCNETGHANA/SORMAS-Project/tree/show_case_contact_without_coordinates_on_map

NEW LINK
https://github.com/ePareto-Information-System/SORMAS-Project/tree/show_case_contact_without_coordinates_on_map

**Comment by isaacanip** [comment]
**_Additional Information_**
If contact/cases don't have location, SORMAS automatically uses the hospital location. Incase the Hospital don't have location, SORMAS uses the district as location. This way, location data is always available for contact or case.

**Comment by isaacanip** [comment]
Path: Cases/Hospitalization/Hospitaliation data/Hospital name

**Additional Information 2**
**Test Reason:** 
Select a hospital with district location intact and see if SORMAS will display case location on map.
**Test Outcome:**
After selecting "Yes" in hospitalization data, the Hospital name section has no field for user to choose the designated hospital. Its after clicking on save before a prompt comes for user to select "Hospital".

![image](https://user-images.githubusercontent.com/60930711/170420880-0a15b609-a1e5-4a57-96b8-79f0ee7f7ff7.png)

**Comment by isaacanip** [comment]
### District location exist but does not show on Map.
### Case Scenario 1
Case person: Helmis Atia    
Case ID: UTPKF4
District: Accra [Has Coordinates (Y/N)= **"Y"**]
Hospital: 37 Military Hospital [Has Coordinates (Y/N)= **"N"**]
**Test Pictures:**
![image](https://user-images.githubusercontent.com/60930711/170423287-0ccd2813-c268-4dff-a97d-fb0bd777d77c.png)

**Comment by isaacanip** [comment]
### Hospital location exist and shows on Map but test failed on the next step .
### Case Scenario 2
Case person: Helmis Atia    
Case ID: UTPKF4
District: Accra [Has Coordinates (Y/N)= **"N"**]
Hospital: 37 Military Hospital [Has Coordinates (Y/N)= **"Y"**]
### Test Outcome: Successful
### Further test outcome: Fail
Fail Description:
After clicking on the location on the Map, an error comes up on the screen. Please see the below picture:
**Test Picture:**
![image](https://user-images.githubusercontent.com/60930711/170436221-42b5d39d-8611-4c79-ad32-454b5cc1b920.png)
### **NB: Test scenario works fine for contact.**

**Comment by isaacanip** [comment]
Issue still Exist

**Comment by isaacanip** [comment]
15.11.2022
GPS coordinates does not show on the Map in 1.74.3 but shows in 1.71.0.
- Click [here](https://watch.screencastify.com/v/RYwYvmUPn8WRyiiuJwqq
) to view video for 1.71.0.
- Click [here](https://watch.screencastify.com/v/TaXZdB0Ry1VoV1wis6sD) to view video for 1.74.3.

**Comment by isaacanip** [comment]
15.11.2022
GPS coordinate does not show on Map in v1.74.3 but shows in 1.71.0.
- Click [here ](https://watch.screencastify.com/v/RYwYvmUPn8WRyiiuJwqq
)to view video for 1.71.0.
- Click [here](https://watch.screencastify.com/v/TaXZdB0Ry1VoV1wis6sD) to view video for 1.74.3.

**Comment by isaacanip** [comment]
15.12.2022
Test GPS Coordinates for Cases and Contacts (NB: Each step is tested separately)
**Cases**
- [x] Configuration
	- [x] District Location
	- [x] Facility Location
- [x] Case Tab: Location
- [x] Case Person Tab: Location

**Contacts**
- [x] Configuration
	- [x] District Location
	- [x] Facility Location
- [x] Contact Person Tab: Location

New Findings: **If facility GPS fields with values are later deleted, the GPS still shows on the Map for the contact.**

**Comment by isaacanip** [comment]
26.03.2023: UAT done.
