### ISSUE TITLE
Add new role, Hospital Supervisor

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#15]
### Situation Description
We have Hospital Informant who is limited to their assigned facility, and cannot view the dashboard.
Facility managers or directors would like a similar limitation but with access to the dashboard.
This is to enable them get an overview of activities and situations going on in the facility.

### Feature Description
Add a new role, Hospital Supervisor, who is limited to their assigned facility and has access to supervisor content like the dashboard.

**Comment by Anthony4m** [comment]
https://github.com/ePareto-Information-System/SORMAS-Project/tree/new_user_role_hospital_supervisor

**Comment by Anthony4m** [comment]
Link to branch 
https://github.com/ePareto-Information-System/SORMAS-Project/tree/new_user_role_hospital_supervisor

**Comment by isaacanip** [comment]
@isaacanip

**Comment by user-yormen** [comment]
![image](https://user-images.githubusercontent.com/24682056/170524666-67669311-a9f0-4324-8965-c31b5f7202d8.png)

**Comment by isaacanip** [comment]
The Hospital Supervisor role is not found on Test UAT.
Kindly see the image below.

![image](https://user-images.githubusercontent.com/60930711/170708875-619b69a4-f1d3-4439-8478-9a40d5f9dcae.png)

**Comment by isaacanip** [comment]
![image](https://user-images.githubusercontent.com/60930711/181200420-ca77a320-5080-46ed-9fba-f9b49c7bf88d.png)

Role: Hospital Supervisor
Username: **FlorOklo**
Password: **PX6erR4LT2NH**

**Description** 
One cannot login with the role as HOSPITAL SUPERVISOR. You can only login successfully after Changing the role and maintaining the same credentials.

**Comment by isaacanip** [comment]
18.11.2022
This issue still persist.
[Click to view UAT video.](https://watch.screencastify.com/v/ehqBJemaX7DpxC7yvKIi)

**Comment by isaacanip** [comment]
15.11.2022
Issue has been resolved. UAT (v1.74.3) was performed on the test environment
