### ISSUE TITLE
Sample Dashboard - Modification

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#17]
There is no wrapping for the area highlighted when screen is magnified above 110%. Issue discussed with Fath.

![image](https://user-images.githubusercontent.com/60930711/151939908-13dfc747-5214-407a-acf9-89cda7126a4b.png)

![image](https://user-images.githubusercontent.com/60930711/151939969-38be8bdc-f7ae-4758-874a-c1d3ebbe9417.png)

**Comment by daveotengo** [comment]
Link to branch https://github.com/ePareto-Information-System/SORMAS-Project/tree/differentiate-sample-count-3

**Comment by isaacanip** [comment]
15.12.2022
UAT done for 1.74.3.
