### ISSUE TITLE
Allow users to change their password

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#21]
### Situation Description
When a user needs their password changed, they have to get an admin user to change it for them.
This means the admin user will see user's new password.
Additionally, user cannot set a custom password. Password is generated by the system.

### Feature Description
Allow user to change their own password.
Also allow user to set a custom password.
There can be an option to generate the password by the system.

**Comment by Anthony4m** [comment]
Link to branch
https://github.com/ePareto-Information-System/SORMAS-Project/tree/Self_reset_password

**Comment by user-yormen** [comment]
Kindly check your commits for my comments
https://github.com/ePareto-Information-System/SORMAS-Project/commits/Self_reset_password

**Comment by user-yormen** [comment]
Nice work @Anthony4m

**Comment by isaacanip** [comment]
Merged successful and UAT Done

**Comment by isaacanip** [comment]
15.11.2022:
UAT done in 1.74.3
