### ISSUE TITLE
User is unable to login. System says "Login failed"

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#23]
### Bug Description
A particular user is unable to login.
We've changed the password, added admin role to the account, but still.
This happens in both web and sormas-rest.

### Steps to Reproduce

1. Enter user's username and password. The username and password of this user will be shared via a separate channel.
2. Click to Login

### Expected Behavior

User should log in successfully

### Screenshots

![image](https://user-images.githubusercontent.com/1176692/153381581-1963638d-2693-4cd8-b9a6-2bfcf34c3a53.png)

### System Details

* Device: web
* SORMAS version: 1.42.3
* Android version/Browser:
* Server URL:
* User Role: Lab Officer

**Comment by user-yormen** [comment]
It turns out some characters in the username provided must be lower case but was in upper case.
Example: The username was supposed to be userNAME but was made USERNAME.

**Comment by faatihi** [comment]
Ah yes. Thanks
