### ISSUE TITLE
Add Field for Case Reinfection

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#35]
### Situation Description

GHS requested for this new feature.to be added.
### Feature Description

Provide a checkbox to tell whether a person is re-infected or not.

**Comment by faatihi** [comment]
Symeda now has this feature. We'll enable the feature and make it available.

**Comment by AnkaAdriana** [comment]
yep, this was high priority
*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2
