### ISSUE TITLE
Ensure that all 16 regions are included in maps overlays

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#44]
### Problem Description

Some regions do not appear on the Map overlays.
### Proposed Solution

Use the shapesfiles from GHS to update the map overlays.

**Comment by user-yormen** [comment]
GITHUB LINK:
https://github.com/ePareto-Information-System/SORMAS-Project/tree/enhancement_change_10_regions_to_16_regions_in_map_overlay

I made modification to the sixteen region shape file, thus regions.shp and made sure these changes reflected on the
 dbf file(regions.dbf)
The 16 regions.shp file was missing some columns, I added these columns, populated them with the missing column's values from the 10 regions and assumed the numbering conversion 

- 	REGION (String 20)
- 	CNTRY_CODE(String 5)
- 	Rowcacode1(String 10)
- 	HRpCode(String 10)

Image of the default 16 regions, thus before changes
![image](https://user-images.githubusercontent.com/24682056/161744423-ace26c80-c917-4e6f-9971-4c111bb12280.png)

Image after the updating the SIXTEEN (16) REGIONS
![image](https://user-images.githubusercontent.com/24682056/161742601-5c353424-6d09-4c20-be2a-7bcffcba6e01.png)

Now the sixteen regions 
![WhatsApp Image 2022-04-05 at 10 33 40 AM](https://user-images.githubusercontent.com/24682056/161743739-0c8596aa-cc76-435f-ad85-ce7e0fc12d81.jpeg)

**Comment by AnkaAdriana** [comment]
Super!!!
*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2

**Comment by faatihi** [comment]
Beautiful, @user-yormen

**Comment by faatihi** [comment]
I've gone through it and it looks great. Good job, man.
One thing, kindly reduce the size of the .shp file.
It's ~3MB. We would like it at ~400KB.

**Comment by user-yormen** [comment]
Sized has been reduced successfully

**Comment by AnkaAdriana** [comment]
Super !!!

**Comment by isaacanip** [comment]
While testing for 16 regions, an error popped up.
### On the Dashboard map layer:
So far as "Show contacts" is selected, clicking on any layer option throws up an error message unless the "Show contact" option is deselected. Once the error shows up, the Epidemiological curve "maximize icon" also throws up an error when user clicks on it. please see picture below:

![image](https://user-images.githubusercontent.com/60930711/170452292-04e26791-f00c-4a59-ac32-6ee40a22bdb4.png)

**Comment by isaacanip** [comment]
Statistics/Cases/Visualization/Map
Clicking on "Generate" is suppose to show the 16 regions.
### Currently "Savanna Region" is not showing under cases. Picture below:
![image](https://user-images.githubusercontent.com/60930711/170465134-ca32a66a-04c7-4ee5-957b-f3e7d8954b45.png)

**Comment by isaacanip** [comment]
Statistics/Contacts/Visualization/Map
Clicking on "Generate" is suppose to show the 16 regions.
### Currently "Upper West Region" is not showing under Contacts. Picture below:

![image](https://user-images.githubusercontent.com/60930711/170727501-d25234b1-bad9-456e-8162-f87c49542d66.png)

**Comment by isaacanip** [comment]
Some Cases and Contacts were transferred to Savannah and Upper west regions and this brought out all the 16 regions.
Issue resolved.

**Comment by isaacanip** [comment]
UAT on 1.74.3
Issues found under the shape files are as follows:

- [ ] Path: "Statistics/Contact/Visualization/Map/Regions": Clicking on the "Generate" button thrown up an error after navigating to the stated path.
- [ ] Path: "Statistics/Contact/Visualization/Map/District": Clicking on the "Generate" button thrown up an error after navigating to the stated path.
![image](https://user-images.githubusercontent.com/60930711/208239125-2477d4da-0d14-4c12-9b89-69e88faf6b05.png)
