### ISSUE TITLE
Setup Mantis BT for use by SORMAS end-user support team

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#45]
### Problem Description
The support team of GHS is getting overwhelmed with issues reported by end-users.
There is the need to organize these issues in order to better manage them without stress.

### Proposed Solution
We've reviewed a number of issue management systems and Mantis Bug Tracker is a viable one.
This tool is to be setup, configured, tested in-depth and then installed for use by the support team.

Tasks:

Dev setup & testing
- [x] Install Mantis BT
- [x] Configure the tool
  - [x] General configuration
  - [x] Email configuration
- [x] Write out use cases to be tested
  - [x] Create issues from email sent from end user to  tech support
  - [x] Automatically assign users to projects with no user assigned 
  - [x] Reassign issues and reports to other teams, users and management
  - [x] Have conversation page on the issue or report
  - [x] Send email notification to a field person when he/she calls to lodge a complaint
  - [x] Check for duplicate issues reported and close the duplicate 
- [x] Remember to document the setup & troubleshoots processes
- [x] Setup on the UAT server
   - [x] Install Mantis BT
   - [x] General Configuration
   - [x] Email Configuration
   - [x] Plugin installation
   - [x] Running cronjob
   - [x] Send Auto response when an issue is created through the mail
   - [x] Testing

**Comment by faatihi** [comment]
Thanks, @Anthony4m for this amazing work.
We took GHS through the tool and they loved it.

A few suggestions were made:

- [x] some mails aren't received in mantis when an officer raises an issue through mail
- [x] Remove support constraint needed to be added for mantis to identify report
- [x] show issue description on "forward issue" page
- [x] send confirmation mail when issue is marked as resolved or closed
- [x] session expires when creating new issue. can we increase expiry length or disable expiry
- [x] add new issue status: in progress. it should be between assigned and resolved
- [x] automatically send mail to caller when issue is created in mantis
- [x] all new issues are categorized under surveillance gh project when created via email. allow admin to re-categorize issues after it is automatically created
- [x] re-arrange issue status dropdown items

**Comment by faatihi** [comment]
If you need to create new issues for the tasks above, kindly do that in the mantis repo and link them to these listed tasks.

**Comment by AnkaAdriana** [comment]
Thanks guys, amazing work indeed!
If not available yet we also need a classification of the issues on
different support levels, more or less SOP for assigning issues
*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2

**Comment by faatihi** [comment]
Nice job, @Anthony4m 

Kindly rearrange the status dropdown list to this:
```
new
acknowledged
assigned
confirmed
in progress
resolved
close
```

I'm not quite sure between `confirmed` and `in progress`, but for now we can have `confirmed` come before it.

Thanks

**Comment by faatihi** [comment]
Also revisit task number seven. I've reworded it for clarity.

**Comment by AnkaAdriana** [comment]
Great 😊
