### ISSUE TITLE
Update the current document for GHANA released features and that of the international level it has been merged with

### ISSUE THREAD

**Issue by user-yormen** [ePareto-Information-System/SORMAS-Project#54]

**Comment by AnkaAdriana** [comment]
Dear Reginald, well done!
Kindly also put push 1.68.0 to training and close it
Thanks
Adriana
*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2
