### ISSUE TITLE
Finalize on Samples Dashboard

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#7]
Joshua and I worked on the Sample Dashboard and we made a pull request to Symeda.
After discussions, we have a few changes to make to complete this task.

https://github.com/hzi-braunschweig/SORMAS-Project/pull/6544https://github.com/hzi-braunschweig/SORMAS-Project/pull/6544

**Comment by faatihi** [comment]
https://github.com/ePareto-Information-System/SORMAS-Project/blob/6ac0bacfcc7479f5ebda5e2c37d0212465d908f0/sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/samples/DashboardSampleFilterLayout.java#L33-L37

- [x] This if clause is probably pretty redundant since this class should only be used for the sample dashboard in the first place

**Comment by faatihi** [comment]
https://github.com/ePareto-Information-System/SORMAS-Project/blob/6ac0bacfcc7479f5ebda5e2c37d0212465d908f0/sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DashboardDataProvider.java#L87-L92

- [x] rename `previousSampleCount` to `previousSampleCounts`
- [x] rename `sampleCount` to `sampleCounts`

**Comment by faatihi** [comment]
https://github.com/ePareto-Information-System/SORMAS-Project/blob/6ac0bacfcc7479f5ebda5e2c37d0212465d908f0/sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java#L974-L979

- [x] We need to rewrite this method to hit the database only once instead of eleven times

**Comment by faatihi** [comment]
https://github.com/ePareto-Information-System/SORMAS-Project/blob/6ac0bacfcc7479f5ebda5e2c37d0212465d908f0/sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleDateType.java#L8-L13

- [x] rename `RECIPIENT` to `RECIPIENCE`

**Comment by faatihi** [comment]
- [x] remember to run `I18nConstantGenerator` after everything.
      To do that: right-click `I18nConstantGenerator.java`, run as ..., Java Application.

**Comment by daveotengo** [comment]
Link to branch https://github.com/ePareto-Information-System/SORMAS-Project/tree/differentiate-sample-count-3

**Comment by isaacanip** [comment]
27.03.2023
- [x] Test results to be relabeled to "Test results by samples".
- [x] Campaigns and samples tabs take you to contact.
- [x] Give a light colour background even when values are zeros  at % columns.

**Comment by isaacanip** [comment]
05.04.2023
Done
