### ISSUE TITLE
Update DHIMS adaptor to be compatible with SORMAS version 1.68.0

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#70]

**Comment by Anthony4m** [comment]
The DHIMS adapter is compatible with sormas version 1.68.0

**Comment by AnkaAdriana** [comment]
Great!

*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2

**Comment by AnkaAdriana** [comment]
Super !
