### ISSUE TITLE
Update Traveler Booking Portal to be compatible with SORMAS version 1.68.0

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#71]

**Comment by Anthony4m** [comment]
https://github.com/ePareto-Information-System/traveler-test-booking/tree/update_test_booking_to_sormas_1.68.0

**Comment by faatihi** [comment]
@Anthony4m, we've moved away from hard-coded configurations to environment variables.
When you're done updating the system, kindly merge changes from this branch before pushing for review:
https://github.com/ePareto-Information-System/traveler-test-booking/tree/use_env_var_for_config

Thanks
