### ISSUE TITLE
Create a subdomain for lab result import adaptor

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#76]
### Problem Description
Currently, the url for the adaptor is http://**test.**surveillancegh.org/toos/schuylab
The url having **test** in it makes it appear to be a testing instance of the adaptor, meanwhile, it is the production instance.

### Proposed Solution
Get a subdomain for the adaptor, so that is looks more appealing.
We can have https://lab-importer.surveillancegh.org/

Much cleaner, simpler and appealing.

**Comment by AnkaAdriana** [comment]
Very good idea, and also the name is indeed simpler, cleaner and more
appealing
*Dr. Adriana Ignea* (MD, DLSHTM)
e-Health Consultant
***@***.***
Tel       +233 248 665 976
skype   Adriana.Ignea2

**Comment by faatihi** [comment]
@AnkaAdriana Thanks

**Comment by AnkaAdriana** [comment]
Thumbs up 👍🏽!
