### ISSUE TITLE
Setup a docker compose configuration for Traveler Booking Portal

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#77]
### Problem Description
GHS is going to be trained on the booking app. We can only set it app for one environment at a time.
That means, when we're about to train, we have to point it to training. Then after training, we restore it back to production.

### Proposed Solution
Setup a compose configuration to enable spinning up multiple instances of this app for various purposes.

**Comment by AnkaAdriana** [comment]
Great idea!

**Comment by user-yormen** [comment]
GITHUB Link
https://github.com/ePareto-Information-System/traveler-test-booking/tree/docker-compose

Created a docker-compose file to the project

**Comment by user-yormen** [comment]
- [x] Create a new branch and 
- [x] Set up docker compose for the app
- [x] Changed the base url to localhost
- [x] Run a test on localhost to make sure all changes work
- [x] Set up the application to point to training
- [x] Created a sub domain with the name lab-booking.surveillancegh.org and set up to pointed to production on that sub domain
- [x] Create a generic endpoint name for the base url
