### ISSUE TITLE
Setup auto deployment of development branch to the test server for UAT

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#87]
### Problem Description
Developers work on features in silos. Whatever they work on is not easily accessible to other developers and QA testers.
This makes it difficult to quickly see progress of developer's work.

### Proposed Solution
Setup an automatic deployment process.
This way, we can have a regular deployment of our work for others to see new features and give instant feedback.

### Possible Alternatives

- [x] Set up new workflow script
- [x] Set up Java JDK
- [x] Set Environment Variables
- [x] Install ant 
- [x] Deploy Serverlibs
- [x] Change wrapper permissions
- [x] Get build apk 
- [x] Build artifacts
- [x] Collect artifacts
- [x] Package artifacts
- [x] Look at the files in the target folder
- [x] Set environment for deploy folder 
- [x] Send deploy folder to test server
- [x] Initiate server update
- [x] Check logs for success or failure 
- [x] Run script when deploy failure
- [x] Fail actions when failure
- [x] Test if fail action works
- [x] try another deploy if update fails
- [x] Test deployed software
- [x] Port to Jenkins 
- [x] Let Sormas compatible with jenkins

**Comment by Anthony4m** [comment]
Branch: https://github.com/ePareto-Information-System/SORMAS-Project/blob/test_auto_deploy/.github/workflows/autodeploy.yml
