### ISSUE TITLE
Lab users unable to login

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#99]
### Bug Description

Lab users do not have the needed permissions to login to SORMAS
### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by faatihi** [comment]
![WhatsApp Image 2022-07-06 at 8 38 51 AM](https://user-images.githubusercontent.com/1176692/177564224-bd82f989-c3b0-45a0-9dfd-8519a519a3fd.jpeg)

**Comment by faatihi** [comment]
This was resolved by adding lab users to glassfish-web.xml and web.xml in sormas-rest
